### ISSUE TITLE
게임 시작 사발 넘어가지 않음

### ISSUE THREAD

**Issue by ChungkeunLee** [wearewolves/werewolf_30m#29]
ㅠㅠ

**Comment by Arepin** [comment]
@rekenber @kijuli @ChungkeunLee 
server/werewolf/game 내의 변경됐던 파일들 모두 배포 당시로 롤백했는데도 마을 시작 안 됩니다. 아무래도 소스 문제가 아니라 최근 3서버가 기간 만료됐다가 다시 살아나면서 초기 셋팅이 덜 됐다든지 바뀐 설정이 있는 듯합니다. 이건 레켄베르님께서 확인해주셔야 할 것 같습니다.

**Comment by ChungkeunLee** [comment]
해결됬습니다.
@rekenber 님 감사합니다.
